Sprint08
MarinaKolbina/ImageFeed pull request #1
Opened 2022-11-30 14:01 UTC by MarinaKolbina

Подготовлено задание для 8 спринта

2022-11-30 16:42 UTC, mmbabaev commented
![Screen Shot 2022-11-30 at 19 42 02](https://user-images.githubusercontent.com/12600807/204856957-60879148-f35f-40f5-9208-17b0bdb9d6df.png)
1. Кнопка лайка расположена без отступов
2. Расстояние между ячейками слишком большое

2022-11-30 16:43 UTC, mmbabaev requested changes

2022-11-30 16:43 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private var photosName = [String]()
Знаю, что по учебнику, но я бы называл `photosName` -> `photoNames`

2022-12-08 16:31 UTC, MarinaKolbina commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private var photosName = [String]()
не могу коммент оставить к замечанию касательно расстояние между ячейками таблицы - а где можно исправить данный параметр?

2022-12-08 17:10 UTC, MarinaKolbina commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private var photosName = [String]()
нашла, прислала на проверку снова

2022-12-15 16:24 UTC, MarinaKolbina commented
@mmbabaev Подготовила исправления после ревью - приношу извинения, что в эту ветку попал кусок нового спринта - начала делать не подумав в старой ветке(

2023-02-07 16:32 UTC, merged