Sprint09
MarinaKolbina/ImageFeed pull request #2
Opened 2022-12-28 20:51 UTC by MarinaKolbina

Подготовлено задание для 9 спринта

2022-12-29 22:16 UTC, mmbabaev requested changes

2022-12-29 22:16 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let viewController = segue.destination as! SingleImageViewController
чтобы не было `as!`, можно приведение типа тоже положить как условие в `if`

2022-12-29 22:16 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let indexPath = sender as! IndexPath
и здесь тоже

2022-12-29 22:16 UTC, mmbabaev commented on ImageFeed/ProfileView/ProfileViewController.swift
> +        let label1 = UILabel()
лучше не называть так переменные. У вас лейбл для имени, назовите `nameLabel`

2022-12-29 22:16 UTC, mmbabaev commented on ImageFeed/ProfileView/ProfileViewController.swift
> +        let label2 = UILabel()
loginLabel? emailLabel?

2022-12-29 22:16 UTC, mmbabaev commented on ImageFeed/ProfileView/ProfileViewController.swift
> +    private func didTapButton() {
непонятно какая кнопка нажата

2022-12-29 22:16 UTC, mmbabaev commented on ImageFeed/SingleImageViewController/SingleImageViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
private

2022-12-29 22:16 UTC, mmbabaev commented on ImageFeed/SingleImageViewController/SingleImageViewController.swift
> +class SingleImageViewController: UIViewController {
в продакшн проектах часто видел, что классы делают `final`, если от них не планируется создавать наследников

2022-12-29 22:16 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private let ShowSingleImageSegueIdentifier = "ShowSingleImage"
принято с маленьких буквы называть переменные, константы тоже

2022-12-30 16:25 UTC, MarinaKolbina commented on ImageFeed/ProfileView/ProfileViewController.swift
> +    private func didTapButton() {
а можно тут немного развернуть, не совсем понятен комментарий)

2023-02-07 16:32 UTC, merged