Sprint10
MarinaKolbina/ImageFeed pull request #3
Opened 2023-01-10 15:11 UTC by MarinaKolbina

Подготовлено задание для 10 спринта

2023-01-11 14:26 UTC, IBDesignable commented
Обрати внимание, что структура проекта расходится с физическим расположением файлов. Давай наведем порядок в этом. 

А файл, лежащий в директории git обычно лежит в корне проекта и называется так '.gitignore'
<img width="338" alt="Снимок экрана 2023-01-11 в 16 24 04" src="https://user-images.githubusercontent.com/121577115/211830731-7660bdd1-f35c-4596-9b0f-cf64914e1838.png">

2023-01-11 15:06 UTC, IBDesignable commented
предыдущие ПР можно закрыть

2023-01-22 11:44 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
> +        }
1. Перевод на главную очередь неправильно сделан и бессмыслен. Так как метод уже на главном потоке вызывается. Зато внутри комплишена fetchOAuthToken действия не гарантированно происходят не на главном потоке, там как раз и нужно свитч обернуть в DispatchQueue.main.async
2. Сейчас пользователь дает разрешение на авторизацию, но дальше ничего не проиходит. Надо закрыть webView хотя бы: vc.dismiss 

Это блокирующие замечания, не могу пройти авторизацию без этого исправления

2023-01-22 11:54 UTC, IBDesignable requested changes

2023-01-22 11:54 UTC, IBDesignable commented on ImageFeed/Auth/OAuthTokenResponseBody.swift
> +    }
отступы на там менье должны быть, не забывай после копипасты проходить по файлу и делать control+i)

2023-01-22 11:54 UTC, IBDesignable commented on ImageFeed/Models/Constants.swift
> +let TokenURL = "https://unsplash.com/oauth/token"
Здесь обычно принято оборачивать в enum Constants, глобальный контекст принято избегать. Ну и я не любитель исключения правила camelCase для констант/свойств/переменных. 
```
enum Constants {
static let accessKey = "..."
}
```

2023-01-22 11:54 UTC, IBDesignable commented on ImageFeed/Models/OAuth2TokenStorage.swift
> +    }
здесь два пробела, вместо 4х, давай поправим control+i

2023-01-22 11:54 UTC, IBDesignable commented on ImageFeed/ProfileView/ProfileViewController.swift
> +        let profileImage = UIImage(named: "userpick")
1) пропущен super.viewDidLoad 
2) Здесь ты создаешь и леаутишь внешний вид экрана, при этом ссылки на объекты не оствляешь. Так можно делать, если не предполагается менять состояние вью по мере жизни экрана, но очевидно с экраном профиля это будет не так: понадобится выставлять аватарку, имя, ник и био профиля, поэтому нам бы пригодились приватные свойства в классе

2023-01-22 11:54 UTC, IBDesignable commented on ImageFeed/Splash/SplashViewController.swift
> +        }
предлагаю вынести этот код в отдельную функцию, например chooseScenario (showNextFlow), так как возможно пригодится вызывать ее больше одного раза

2023-01-22 11:54 UTC, IBDesignable commented on ImageFeed/Splash/SplashViewController.swift
> +    func authViewController(_ vc: AuthViewController, didAuthenticateWithCode code: String) {
здесь излишне передавать информацию о коде и уж тем более повторно фетчить токен, ты это уже делаешь на экране авторизации. 
Поэтому предлагаю:
- убрать лишний параметр, 
- поменять нейминг (didAuthentificate), который будет означать успешную авторизацию, когда надо бы выбрать куда двигаться дальше (выбрать сценарий или флоу)

2023-01-22 11:54 UTC, IBDesignable commented on ImageFeed/Splash/SplashViewController.swift
> +        dismiss(animated: true) { [weak self] in
обращу внимание, что здесь dismiss неявно вызывается на self, то есть на сплеш скрине, что может привести к тому, что экран будет выгружен из памяти раньше чем закончат выполняться следующие асинхронные функции. 

Предполагаю, что имелось ввиду другое, и здесь нужно задисмисить AuthViewController

2023-01-22 11:54 UTC, IBDesignable commented on ImageFeed/Splash/SplashViewController.swift
> +    }
соотвественно, как описала выше, это уже не нужно 

ПС: я вижу подобный подход не только у тебя, если так показано в уроке, пожалуйста, тегни меня в этом комменте

2023-01-22 12:00 UTC, IBDesignable commented
Да и, в вебвью контроллера не реализована кнопка назад. В случае тупикого сценария со стороны Unsplash пользователю сложно будет вернуться назад на авторизацию. Кажется, это надо было сделать тоже, посмотри пожалуйста

2023-02-01 17:01 UTC, MarinaKolbina commented on ImageFeed/Splash/SplashViewController.swift
> +    }
@IBDesignable добрый день! да, этот кусок кода в таком виде присутствует в курсе. Картинка не прикладывается, но код в таком виде можно найти тут - Спринт 11/14: 11 → Тема 1/7: Swift Package Manager → Урок 4/4 
В связи с этим, я что-то не очень понимаю, как это надо исправлять ))

2023-02-01 17:44 UTC, MarinaKolbina commented
> Да и, в вебвью контроллера не реализована кнопка назад. В случае тупикого сценария со стороны Unsplash пользователю сложно будет вернуться назад на авторизацию. Кажется, это надо было сделать тоже, посмотри пожалуйста
@IBDesignable насколько я могу заметить, реализации этой кнопки не было

2023-02-02 20:22 UTC, IBDesignable commented on ImageFeed/Splash/SplashViewController.swift
> +    }
Приношу извинения, так действительно рекомендуют авторы, была не права

2023-02-02 20:32 UTC, IBDesignable approved these changes
Все корректно. Можно мерджить

2023-02-02 20:32 UTC, IBDesignable commented on ImageFeed/ProfileView/ProfileViewController.swift
> +        logOutButton.tintColor = .red
В макетах другой цвет у кнопки

2023-02-02 20:33 UTC, IBDesignable commented on ImageFeed/ProfileView/ProfileViewController.swift
> +        logOutButton.tintColor = .red
Не крит, но стоит поправить

2023-02-07 16:33 UTC, merged